version: "3.1"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Th1sI5T0t4l1yAR3AlP45sW0rD
    ports:
      - 1433:1433

  client:
    build:
      context: ./client
    image: "todo/client:${TAG:-latest}"
    ports:
      - "3000:80"
    environment:
      - AUTH0_SECRET
      - AUTH0_BASE_URL
      - AUTH0_ISSUER_BASE_URL
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - BASE_URL

  server:
    build:
      context: ./server
    image: "todo/server:${TAG:-latest}"
    ports:
      - "5247:80"
    environment:
      - Auth0__Authority
      - Auth0__Audience
      - ConnectionStrings__db="Data source=sql;Initial Catalog=Server;User Id=sa;Password=Th1sI5T0t4l1yAR3AlP45sW0rD;Encrypt=False;"
    depends_on:
      - db
