version: "3.1"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Th1sI5T0t4l1yAR3AlP45sW0rD
    ports:
      - 1433:1433
